### ISSUE TITLE
Help needed with the Test suite (GA episode 8)

### ISSUE THREAD

**Issue by MrKligson** [stemcstudio/stemcstudio#70]
I'm trying to follow along with episode 8 of Geometric algebra, but I'm running into problems. I added the testing framework from the project menu, but tests.ts and e2ga.spec.ts are riddled with error messages, which i don't see in the video. I did watch the stemcstudio video on adding testing, which didn't help, and the user guide has (as far as I could tell) nothing concerning testing. 

Despite the errors, things seemed to work, but when i added the checkEQ function i got these messages and failure on the test results page:
```
TypeError: expect(...).ToBe is not a function in https://www.stemcstudio.com/gists/2acaf00d75b5e0ea379e96dee3020476 (line 41)

checkEQ@https://www.stemcstudio.com/gists/2acaf00d75b5e0ea379e96dee3020476:41:31
geometricSpec/</<@https://www.stemcstudio.com/gists/2acaf00d75b5e0ea379e96dee3020476:71:32
<Jasmine>
```
Below are some screenshots

If you'd like to take a look, I've uploaded it to github: (https://www.stemcstudio.com/gists/2acaf00d75b5e0ea379e96dee3020476)

I'm just stumped at this point

![e2ga spec](https://github.com/user-attachments/assets/3fbee4cf-0103-457e-a44b-e0e349aeb372)
![tests ts](https://github.com/user-attachments/assets/9f1623c2-c0b9-4d70-ba92-7e96c56d6641)
![e2ga spec ts-tooltip](https://github.com/user-attachments/assets/b7562f73-be05-47c1-bdb8-06f2d01bf32e)

**Comment by MrKligson** [comment]
I did notice my type in checkEQ now, so i am able to test my stuff.
All the errors are very confusing though

**Comment by stemcstudio** [comment]
@MrKligson

Apologies for not having replied MUCH sooner.

This situation can be fixed with some configuration changes in your project. I apologize that this is not well-documented at present.

I would suggest that you make the following changes so that you can better understand what is going on while the situation is remedied.

a) UNCHECK "Hide Configuration Files" in "Project Settings". This will, most importantly, give you access to the "studio.config.json" file.
b) CHECK "Show Generated Files" in "Project Settings". This will let you see some of the readonly files that are intermediate to creating the final output.
c) UPDATE your dependency on "jasmine" to "5.4.0" in "package.json" file. This just gets you current, but why not?
d) In "studio.config.json" file, ensure that there is an override for jasmine that looks like this...

  "overrides": [
        {
            "name": "jasmine",
            "version": "5.4.0",
            "system": null,
            "types": "https://stemcstudio.com/vendor/jasmine@5.4.0/index.d.ts"
        }
    ],

This is the crucial step. We are ensuring that the type definitions for jasmine are loaded by stemcstudio. Note that setting "system" to null says that we don't need the EcmaScript modules associated with jasmine. This is because we are loading the scripts through the tests.html file.

e) You don't actually need the lines in "tests.html" that load the jasmine css and js files. stemcstudio can figure that out from the jasmine dependency.

For an example, see https://www.stemcstudio.com/gists/694bb1c4d10c0c0c39dfa0f943522f2f

If this all seems a bit of a kludge, well maybe it is; stemcstudio has undergone an evolution from old-fashioned script loading to EcmaScript modules and it is still using jasmine through script loading.
